services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: tracker-app
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        ports:
            - "9000:9000"
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8099:80"
        depends_on:
            - app
        networks:
            - laravel

    database:
        image: postgres:13
        container_name: postgres
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        networks:
            - laravel
        volumes:
            - pgdata:/var/lib/postgresql/data

    node:
        platform: linux/arm64/v8 #this line is optional if you are using Mac Silicon chip (M1/M2/M3)
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        container_name: my-laravel-node
        ports:
            - "3000:3000"
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - /var/www/node_modules
        networks:
            - laravel

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    pgdata:
