version: '3.8'

services:
    # Laravel Backend
    laravel:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_DATABASE=laravel
            - DB_USERNAME=user
            - DB_PASSWORD=password
            - CACHE_DRIVER=redis
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - postgres
            - redis
        networks:
            - app-network

    # Nginx
    nginx:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/public
        ports:
            - "8989:80"
        depends_on:
            - laravel
        networks:
            - app-network

    # PostgreSQL
    postgres:
        image: postgres:13
        container_name: postgres
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB= laravel
            - POSTGRES_USER= user
            - POSTGRES_PASSWORD= password
        ports:
            - "5432:5432"
        networks:
            - app-network

    # Redis
    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        networks:
            - app-network

# Volumes
volumes:
    postgres_data:

# Networks
networks:
    app-network:
        driver: bridge
